brave-intl/challenge-bypass-server

- Dockerfile
I have added a dockerfile to containerize this repo
> add a dockerfile

- Dockerfile
- go.mod
- go.sum
- server/db.go
- server/server.go
- server/server_test.go
- server/tokens.go
I also refactored the tests to use a `testify` suite
> Add bulk redeem endpoint

- .prometheus/prometheus.yml
- Dockerfile
- btd/issuer.go
- docker-compose.yml
- go.mod
- go.sum
- server/db.go
- server/server.go
- server/server_test.go
- server/tokens.go
- utils/metrics/db_stats.go
- utils/metrics/db_stats_test.go
Fixes #11 - by adding prom instrumentation to more clearly visualize timings and operation counts. Also provides db connection stats to prom.
> Adding more prometheus metric gathering

- Dockerfile
- go.mod
- server/db.go
- server/issuers.go
- server/server_test.go
> Endpoint and DB

- main.go
- server/db.go
- server/dynamo.go
- server/issuers.go
- server/server.go
- server/tokens.go
Having more visibility of what happens in the bypass server with richer logs.
> Add logging to bypass server

- server/cron.go
- server/issuers.go
- server/server_test.go
- server/tokens.go
> Tainted Tokens #2 Updates

- server/db.go
removed close on nil row
resolves #133
> bug: redeem token rows nil pointer

- kafka/main.go
- kafka/signed_blinded_token_issuer_handler.go
- kafka/signed_token_redeem_handler.go
- main.go
- server/db.go
- server/dynamo.go
- server/tokens.go
- utils/errors.go
This reverts commit 7001df0f45df583ba78a8272f18fc171d0c84fe2.
Look at #154 to confirm that the eventual prod merge would do what is expected.
> Revert "Improve batching implementation"

- go.mod
- go.sum
- kafka/signed_blinded_token_issuer_handler.go
- server/db.go
This PR adds issuer valid to and issuer valid from fields to the associated data. Also renames the issuer column in the cron job.
resolves #158
> Add issuer valid to and issuer valid from fields to the associated data

- server/issuers.go
> unique issuers

- avro/generated/signing_result_v2.go
- avro/generated/signing_result_v2_set.go
- avro/schemas/signing_result_v2.avsc
- kafka/avro_test.go
- kafka/signed_blinded_token_issuer_handler.go
- utils/test/random.go
This PR adds blinded tokens to the signing order result
resolves #175
> added blinded creds to schema

- avro/generated/redeem_result.go
- avro/generated/redeem_result_set.go
- avro/generated/redeem_result_status.go
- avro/schemas/redeem_result.avsc
- kafka/main.go
- kafka/result_and_error.go
- kafka/signed_blinded_token_issuer_handler.go
- kafka/signed_token_redeem_handler.go
- main.go
- server/db.go
- server/dynamo.go
- server/tokens.go
- utils/errors.go
Second of 3 PRs to bring the correctness features from ads-stage that were removed to make master merge possible.
> DynamoDB Multiple Error Response

- kafka/signed_blinded_token_issuer_handler.go
- server/issuers.go
- utils/errors.go
adding unwrap to processing error and fixing the way we check errors  for get issuer
> Get Issuer Error Unwrap

- migrations/0007_issuers_v3.up.sql
Because the Ads `challenge-bypass-server` Postgres database contains issuers which share `issuer_type`s, the existing migration fails. This change updates the migration to take only the issuer with the `expires_at` the furthest in the future from the set which share an `issuer_type`. Then, for the keys, it takes all keys and inserts them with the `issuer_id` associated with the `v3_issuer` with the key's `issuer_type` that was selected in the previous step, rather than the `issuer_id` to which the key was originally associated. Because we use a combination of `issuer_type` and `cohort` for key selection there should be no interface change to support this, though there may be a small query update to follow.
> Update migration to accomodate ads-cbp database

- kafka/signed_token_redeem_handler.go
fixes: https://github.com/brave-intl/challenge-bypass-server/issues/257
> remove version 3 processing for redeem kafka processor

- Dockerfile
https://stackoverflow.com/questions/76094428/debian-stretch-repositories-404-not-found
> Hack around Debian stretch package location change

- Dockerfile
- go.mod
- go.sum
eliminates need to use rust nightly to build
> update cbr-ffi revision to 1.0.1

- Dockerfile
- go.mod
- go.sum
This reverts commit a3052f995deb64aa00dc3b4131bf797579a579fe.
> Revert FFI Upgrade

- kafka/signed_token_redeem_handler.go
Reverts brave-intl/challenge-bypass-server#516, which reverted https://github.com/brave-intl/challenge-bypass-server/pull/502.
So this reintroduces the changes added in https://github.com/brave-intl/challenge-bypass-server/pull/502.
> Reinstate: "Allow Redemption With Non-Current Valid Keys"

- go.sum
- kafka/signed_token_redeem_handler.go
Attempts to resolve panic thrown by `challenge-bypass-ristretto-ffi`
> fix: check signing key is not nil

- kafka/main.go
> fix: revert CPU constraint

- kafka/main.go
- kafka/signed_blinded_token_issuer_handler.go
- kafka/signed_token_redeem_handler.go
- main.go
- server/db.go
- server/issuers.go
- server/server.go
- server/tokens.go
- Fix existing metrics
- Add API metrics
- Add Kafka metrics
- Add /metrics endpoint on port 9090 for scraping
> Fix and Add Prometheus Metrics

- go.mod
- kafka/main.go
- main.go
- server/server.go
- server/server_test.go
- utils/alert/alert.go
- utils/alert/alert_test.go
- utils/metrics/register.go
Put alerting back in dev for testing.
> Add Log Alerting to Dev
